services:

  postgres:
    image: 'postgres:latest'
    container_name: 'tododb'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
  adminer:
    image: adminer:latest
    ports:
      - 8082:8080